trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
          - script: |
              pip install -r requirements.txt
              pytest
            displayName: 'Install dependencies and run tests'
          - task: Docker@2
            inputs:
              containerRegistry: 'your-container-registry'
              repository: 'youracrname.azurecr.io/ml-model'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
  - stage: Deploy
    dependsOn: Build
    jobs:
      - job: DeployToAKS
        steps:
          - task: Kubernetes@1
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'your-azure-subscription'
              azureResourceGroup: 'your-resource-group'
              kubernetesCluster: 'your-kubernetes-cluster'
              namespace: 'default'
              command: 'apply'
              useConfigurationFile: true
              configuration: 'k8s-deployment.yaml'
